package com.ericlai.express.dto;

public class Address {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.ADDR_ID
     *
     * @mbggenerated Tue Feb 02 19:49:20 CST 2016
     */
    private Integer addrId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.PERSON_ID
     *
     * @mbggenerated Tue Feb 02 19:49:20 CST 2016
     */
    private String personId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.ADDR_INFO
     *
     * @mbggenerated Tue Feb 02 19:49:20 CST 2016
     */
    private String addrInfo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.DELETE_FLAG
     *
     * @mbggenerated Tue Feb 02 19:49:20 CST 2016
     */
    private String deleteFlag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.ADDR_ID
     *
     * @return the value of address.ADDR_ID
     *
     * @mbggenerated Tue Feb 02 19:49:20 CST 2016
     */
    public Integer getAddrId() {
        return addrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.ADDR_ID
     *
     * @param addrId the value for address.ADDR_ID
     *
     * @mbggenerated Tue Feb 02 19:49:20 CST 2016
     */
    public void setAddrId(Integer addrId) {
        this.addrId = addrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.PERSON_ID
     *
     * @return the value of address.PERSON_ID
     *
     * @mbggenerated Tue Feb 02 19:49:20 CST 2016
     */
    public String getPersonId() {
        return personId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.PERSON_ID
     *
     * @param personId the value for address.PERSON_ID
     *
     * @mbggenerated Tue Feb 02 19:49:20 CST 2016
     */
    public void setPersonId(String personId) {
        this.personId = personId == null ? null : personId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.ADDR_INFO
     *
     * @return the value of address.ADDR_INFO
     *
     * @mbggenerated Tue Feb 02 19:49:20 CST 2016
     */
    public String getAddrInfo() {
        return addrInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.ADDR_INFO
     *
     * @param addrInfo the value for address.ADDR_INFO
     *
     * @mbggenerated Tue Feb 02 19:49:20 CST 2016
     */
    public void setAddrInfo(String addrInfo) {
        this.addrInfo = addrInfo == null ? null : addrInfo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.DELETE_FLAG
     *
     * @return the value of address.DELETE_FLAG
     *
     * @mbggenerated Tue Feb 02 19:49:20 CST 2016
     */
    public String getDeleteFlag() {
        return deleteFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.DELETE_FLAG
     *
     * @param deleteFlag the value for address.DELETE_FLAG
     *
     * @mbggenerated Tue Feb 02 19:49:20 CST 2016
     */
    public void setDeleteFlag(String deleteFlag) {
        this.deleteFlag = deleteFlag == null ? null : deleteFlag.trim();
    }
}