package com.ericlai.express.dto;

public class Admin {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.ADMIN_ID
     *
     * @mbggenerated Tue Jan 26 00:21:57 CST 2016
     */
    private String adminId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.ADMIN_AUTH
     *
     * @mbggenerated Tue Jan 26 00:21:57 CST 2016
     */
    private String adminAuth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.PERSON_ID
     *
     * @mbggenerated Tue Jan 26 00:21:57 CST 2016
     */
    private String personId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.ADMIN_ID
     *
     * @return the value of admin.ADMIN_ID
     *
     * @mbggenerated Tue Jan 26 00:21:57 CST 2016
     */
    public String getAdminId() {
        return adminId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.ADMIN_ID
     *
     * @param adminId the value for admin.ADMIN_ID
     *
     * @mbggenerated Tue Jan 26 00:21:57 CST 2016
     */
    public void setAdminId(String adminId) {
        this.adminId = adminId == null ? null : adminId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.ADMIN_AUTH
     *
     * @return the value of admin.ADMIN_AUTH
     *
     * @mbggenerated Tue Jan 26 00:21:57 CST 2016
     */
    public String getAdminAuth() {
        return adminAuth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.ADMIN_AUTH
     *
     * @param adminAuth the value for admin.ADMIN_AUTH
     *
     * @mbggenerated Tue Jan 26 00:21:57 CST 2016
     */
    public void setAdminAuth(String adminAuth) {
        this.adminAuth = adminAuth == null ? null : adminAuth.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.PERSON_ID
     *
     * @return the value of admin.PERSON_ID
     *
     * @mbggenerated Tue Jan 26 00:21:57 CST 2016
     */
    public String getPersonId() {
        return personId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.PERSON_ID
     *
     * @param personId the value for admin.PERSON_ID
     *
     * @mbggenerated Tue Jan 26 00:21:57 CST 2016
     */
    public void setPersonId(String personId) {
        this.personId = personId == null ? null : personId.trim();
    }
}