package com.ericlai.express.dto;

public class Dynamicqr {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dynamicqr.pacId
     *
     * @mbggenerated Mon May 09 00:54:24 CST 2016
     */
    private String pacid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dynamicqr.msg
     *
     * @mbggenerated Mon May 09 00:54:24 CST 2016
     */
    private String msg;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dynamicqr.pacId
     *
     * @return the value of dynamicqr.pacId
     *
     * @mbggenerated Mon May 09 00:54:24 CST 2016
     */
    public String getPacid() {
        return pacid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dynamicqr.pacId
     *
     * @param pacid the value for dynamicqr.pacId
     *
     * @mbggenerated Mon May 09 00:54:24 CST 2016
     */
    public void setPacid(String pacid) {
        this.pacid = pacid == null ? null : pacid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dynamicqr.msg
     *
     * @return the value of dynamicqr.msg
     *
     * @mbggenerated Mon May 09 00:54:24 CST 2016
     */
    public String getMsg() {
        return msg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dynamicqr.msg
     *
     * @param msg the value for dynamicqr.msg
     *
     * @mbggenerated Mon May 09 00:54:24 CST 2016
     */
    public void setMsg(String msg) {
        this.msg = msg == null ? null : msg.trim();
    }
}