package com.ericlai.express.dto;

public class Package {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column package.PAC_ID
     *
     * @mbggenerated Tue Feb 02 19:49:20 CST 2016
     */
    private String pacId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column package.SEND_ID
     *
     * @mbggenerated Tue Feb 02 19:49:20 CST 2016
     */
    private String sendId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column package.REC_ID
     *
     * @mbggenerated Tue Feb 02 19:49:20 CST 2016
     */
    private String recId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column package.PAC_STATUS
     *
     * @mbggenerated Tue Feb 02 19:49:20 CST 2016
     */
    private String pacStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column package.POS_ID
     *
     * @mbggenerated Tue Feb 02 19:49:20 CST 2016
     */
    private String posId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column package.DELETE_FLAG
     *
     * @mbggenerated Tue Feb 02 19:49:20 CST 2016
     */
    private String deleteFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column package.ADDR_ID
     *
     * @mbggenerated Tue Feb 02 19:49:20 CST 2016
     */
    private Integer addrId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column package.PAC_ID
     *
     * @return the value of package.PAC_ID
     *
     * @mbggenerated Tue Feb 02 19:49:20 CST 2016
     */
    public String getPacId() {
        return pacId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column package.PAC_ID
     *
     * @param pacId the value for package.PAC_ID
     *
     * @mbggenerated Tue Feb 02 19:49:20 CST 2016
     */
    public void setPacId(String pacId) {
        this.pacId = pacId == null ? null : pacId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column package.SEND_ID
     *
     * @return the value of package.SEND_ID
     *
     * @mbggenerated Tue Feb 02 19:49:20 CST 2016
     */
    public String getSendId() {
        return sendId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column package.SEND_ID
     *
     * @param sendId the value for package.SEND_ID
     *
     * @mbggenerated Tue Feb 02 19:49:20 CST 2016
     */
    public void setSendId(String sendId) {
        this.sendId = sendId == null ? null : sendId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column package.REC_ID
     *
     * @return the value of package.REC_ID
     *
     * @mbggenerated Tue Feb 02 19:49:20 CST 2016
     */
    public String getRecId() {
        return recId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column package.REC_ID
     *
     * @param recId the value for package.REC_ID
     *
     * @mbggenerated Tue Feb 02 19:49:20 CST 2016
     */
    public void setRecId(String recId) {
        this.recId = recId == null ? null : recId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column package.PAC_STATUS
     *
     * @return the value of package.PAC_STATUS
     *
     * @mbggenerated Tue Feb 02 19:49:20 CST 2016
     */
    public String getPacStatus() {
        return pacStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column package.PAC_STATUS
     *
     * @param pacStatus the value for package.PAC_STATUS
     *
     * @mbggenerated Tue Feb 02 19:49:20 CST 2016
     */
    public void setPacStatus(String pacStatus) {
        this.pacStatus = pacStatus == null ? null : pacStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column package.POS_ID
     *
     * @return the value of package.POS_ID
     *
     * @mbggenerated Tue Feb 02 19:49:20 CST 2016
     */
    public String getPosId() {
        return posId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column package.POS_ID
     *
     * @param posId the value for package.POS_ID
     *
     * @mbggenerated Tue Feb 02 19:49:20 CST 2016
     */
    public void setPosId(String posId) {
        this.posId = posId == null ? null : posId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column package.DELETE_FLAG
     *
     * @return the value of package.DELETE_FLAG
     *
     * @mbggenerated Tue Feb 02 19:49:20 CST 2016
     */
    public String getDeleteFlag() {
        return deleteFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column package.DELETE_FLAG
     *
     * @param deleteFlag the value for package.DELETE_FLAG
     *
     * @mbggenerated Tue Feb 02 19:49:20 CST 2016
     */
    public void setDeleteFlag(String deleteFlag) {
        this.deleteFlag = deleteFlag == null ? null : deleteFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column package.ADDR_ID
     *
     * @return the value of package.ADDR_ID
     *
     * @mbggenerated Tue Feb 02 19:49:20 CST 2016
     */
    public Integer getAddrId() {
        return addrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column package.ADDR_ID
     *
     * @param addrId the value for package.ADDR_ID
     *
     * @mbggenerated Tue Feb 02 19:49:20 CST 2016
     */
    public void setAddrId(Integer addrId) {
        this.addrId = addrId;
    }
}