package com.ericlai.express.dto;

public class Person {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person.PERSON_ID
     *
     * @mbggenerated Tue Feb 02 19:49:20 CST 2016
     */
    private String personId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person.ID_CRL
     *
     * @mbggenerated Tue Feb 02 19:49:20 CST 2016
     */
    private String idCrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person.NAME
     *
     * @mbggenerated Tue Feb 02 19:49:20 CST 2016
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person.PHONE
     *
     * @mbggenerated Tue Feb 02 19:49:20 CST 2016
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person.LOG_PW
     *
     * @mbggenerated Tue Feb 02 19:49:20 CST 2016
     */
    private String logPw;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person.GENDER
     *
     * @mbggenerated Tue Feb 02 19:49:20 CST 2016
     */
    private String gender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person.LOG_NM
     *
     * @mbggenerated Tue Feb 02 19:49:20 CST 2016
     */
    private String logNm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person.LOG_NM
     *
     * @mbggenerated Tue Feb 02 19:49:20 CST 2016
     */
    private String deleteFlag;

    public String getDeleteFlag() {
        return deleteFlag;
    }

    public void setDeleteFlag(String deleteFlag) {
        this.deleteFlag = deleteFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person.PERSON_ID
     *
     * @return the value of person.PERSON_ID
     *
     * @mbggenerated Tue Feb 02 19:49:20 CST 2016
     */
    public String getPersonId() {
        return personId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person.PERSON_ID
     *
     * @param personId the value for person.PERSON_ID
     *
     * @mbggenerated Tue Feb 02 19:49:20 CST 2016
     */
    public void setPersonId(String personId) {
        this.personId = personId == null ? null : personId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person.ID_CRL
     *
     * @return the value of person.ID_CRL
     *
     * @mbggenerated Tue Feb 02 19:49:20 CST 2016
     */
    public String getIdCrl() {
        return idCrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person.ID_CRL
     *
     * @param idCrl the value for person.ID_CRL
     *
     * @mbggenerated Tue Feb 02 19:49:20 CST 2016
     */
    public void setIdCrl(String idCrl) {
        this.idCrl = idCrl == null ? null : idCrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person.NAME
     *
     * @return the value of person.NAME
     *
     * @mbggenerated Tue Feb 02 19:49:20 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person.NAME
     *
     * @param name the value for person.NAME
     *
     * @mbggenerated Tue Feb 02 19:49:20 CST 2016
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person.PHONE
     *
     * @return the value of person.PHONE
     *
     * @mbggenerated Tue Feb 02 19:49:20 CST 2016
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person.PHONE
     *
     * @param phone the value for person.PHONE
     *
     * @mbggenerated Tue Feb 02 19:49:20 CST 2016
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person.LOG_PW
     *
     * @return the value of person.LOG_PW
     *
     * @mbggenerated Tue Feb 02 19:49:20 CST 2016
     */
    public String getLogPw() {
        return logPw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person.LOG_PW
     *
     * @param logPw the value for person.LOG_PW
     *
     * @mbggenerated Tue Feb 02 19:49:20 CST 2016
     */
    public void setLogPw(String logPw) {
        this.logPw = logPw == null ? null : logPw.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person.GENDER
     *
     * @return the value of person.GENDER
     *
     * @mbggenerated Tue Feb 02 19:49:20 CST 2016
     */
    public String getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person.GENDER
     *
     * @param gender the value for person.GENDER
     *
     * @mbggenerated Tue Feb 02 19:49:20 CST 2016
     */
    public void setGender(String gender) {
        this.gender = gender == null ? null : gender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person.LOG_NM
     *
     * @return the value of person.LOG_NM
     *
     * @mbggenerated Tue Feb 02 19:49:20 CST 2016
     */
    public String getLogNm() {
        return logNm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person.LOG_NM
     *
     * @param logNm the value for person.LOG_NM
     *
     * @mbggenerated Tue Feb 02 19:49:20 CST 2016
     */
    public void setLogNm(String logNm) {
        this.logNm = logNm == null ? null : logNm.trim();
    }
}