package com.ericlai.express.dto;

public class Poster {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column poster.POS_ID
     *
     * @mbggenerated Tue Feb 02 19:49:20 CST 2016
     */
    private String posId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column poster.PERSON_ID
     *
     * @mbggenerated Tue Feb 02 19:49:20 CST 2016
     */
    private String personId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column poster.POS_PAC_ID
     *
     * @mbggenerated Tue Feb 02 19:49:20 CST 2016
     */
    private String posPacId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column poster.DELETE_FLAG
     *
     * @mbggenerated Tue Feb 02 19:49:20 CST 2016
     */
    private String deleteFlag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column poster.POS_ID
     *
     * @return the value of poster.POS_ID
     *
     * @mbggenerated Tue Feb 02 19:49:20 CST 2016
     */
    public String getPosId() {
        return posId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column poster.POS_ID
     *
     * @param posId the value for poster.POS_ID
     *
     * @mbggenerated Tue Feb 02 19:49:20 CST 2016
     */
    public void setPosId(String posId) {
        this.posId = posId == null ? null : posId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column poster.PERSON_ID
     *
     * @return the value of poster.PERSON_ID
     *
     * @mbggenerated Tue Feb 02 19:49:20 CST 2016
     */
    public String getPersonId() {
        return personId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column poster.PERSON_ID
     *
     * @param personId the value for poster.PERSON_ID
     *
     * @mbggenerated Tue Feb 02 19:49:20 CST 2016
     */
    public void setPersonId(String personId) {
        this.personId = personId == null ? null : personId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column poster.POS_PAC_ID
     *
     * @return the value of poster.POS_PAC_ID
     *
     * @mbggenerated Tue Feb 02 19:49:20 CST 2016
     */
    public String getPosPacId() {
        return posPacId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column poster.POS_PAC_ID
     *
     * @param posPacId the value for poster.POS_PAC_ID
     *
     * @mbggenerated Tue Feb 02 19:49:20 CST 2016
     */
    public void setPosPacId(String posPacId) {
        this.posPacId = posPacId == null ? null : posPacId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column poster.DELETE_FLAG
     *
     * @return the value of poster.DELETE_FLAG
     *
     * @mbggenerated Tue Feb 02 19:49:20 CST 2016
     */
    public String getDeleteFlag() {
        return deleteFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column poster.DELETE_FLAG
     *
     * @param deleteFlag the value for poster.DELETE_FLAG
     *
     * @mbggenerated Tue Feb 02 19:49:20 CST 2016
     */
    public void setDeleteFlag(String deleteFlag) {
        this.deleteFlag = deleteFlag == null ? null : deleteFlag.trim();
    }
}