package com.ericlai.express.dao;

import com.ericlai.express.dto.Dynamicqr;
import org.springframework.stereotype.Repository;

@Repository
public interface DynamicqrMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dynamicqr
     *
     * @mbggenerated Mon May 09 00:54:24 CST 2016
     */
    int deleteByPrimaryKey(String pacid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dynamicqr
     *
     * @mbggenerated Mon May 09 00:54:24 CST 2016
     */
    int insert(Dynamicqr record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dynamicqr
     *
     * @mbggenerated Mon May 09 00:54:24 CST 2016
     */
    int insertSelective(Dynamicqr record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dynamicqr
     *
     * @mbggenerated Mon May 09 00:54:24 CST 2016
     */
    Dynamicqr selectByPrimaryKey(String pacid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dynamicqr
     *
     * @mbggenerated Mon May 09 00:54:24 CST 2016
     */
    int updateByPrimaryKeySelective(Dynamicqr record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dynamicqr
     *
     * @mbggenerated Mon May 09 00:54:24 CST 2016
     */
    int updateByPrimaryKey(Dynamicqr record);
}