package com.ericlai.express.dao;

import com.ericlai.express.dto.Package;
import org.springframework.stereotype.Repository;

@Repository
public interface PackageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table package
     *
     * @mbggenerated Tue Feb 02 19:49:20 CST 2016
     */
    int deleteByPrimaryKey(String pacId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table package
     *
     * @mbggenerated Tue Feb 02 19:49:20 CST 2016
     */
    int insert(Package record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table package
     *
     * @mbggenerated Tue Feb 02 19:49:20 CST 2016
     */
    int insertSelective(Package record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table package
     *
     * @mbggenerated Tue Feb 02 19:49:20 CST 2016
     */
    Package selectByPrimaryKey(String pacId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table package
     *
     * @mbggenerated Tue Feb 02 19:49:20 CST 2016
     */
    int updateByPrimaryKeySelective(Package record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table package
     *
     * @mbggenerated Tue Feb 02 19:49:20 CST 2016
     */
    int updateByPrimaryKey(Package record);
}